apiVersion: apps/v1
kind: Deployment
metadata:
  name: management-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: management-db
  template:
    metadata:
      labels:
        app: management-db
    spec:
      containers:
        - name: management-db
          image: postgres:13.5
          imagePullPolicy: Always
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: management-db-configmap
                  key: DATABASE_NAME

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: management-db-secret
                  key: DATABASE_USERNAME

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: management-db-secret
                  key: DATABASE_PASSWORD

          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: management-db-service
spec:
  selector:
    app: management-db
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
