apiVersion: apps/v1
kind: Deployment
metadata:
  name: management-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: management-frontend
  template:
    metadata:
      labels:
        app: management-frontend
    spec:
      containers:
        - name: management-frontend
          image: kamil20/management-frontend:latest
          imagePullPolicy: Always
          env:
            - name: REACT_APP_API
              value: "management-backend"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: management-frontend-service
spec:
  selector:
    app: management-frontend
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80