const Home = () => {

    return (
        <h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
            <h2>Home</h2>
        </h2>
    )
}

export default Home;